version: '3'

networks:
  docker-symfony-network:

services:

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "7777:80"
    volumes:
      - ./app:/var/www/project
      - ./infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php74-service
      - mysql8-service
    networks:
      - docker-symfony-network

  # php
  php74-service:
    build:
      context: .
      dockerfile: ./infrastructure/php/Dockerfile
    container_name: php74-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - docker-symfony-network

  # mysql
  mysql8-service:
    image: mysql:8
    container_name: mysql8-container
    ports:
      - "4306:3306"
    volumes:
      - ./infrastructure/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    networks:
      - docker-symfony-network
